
export const PAPER_PALETTE = [
    { name: "CVPR", color: "#09a6f3" },
    { name: "ICLR", color: "#76c893" },
    { name: "NeurIPS", color: "#9d4edd" },
    { name: "ICML", color: "#211e1f" },
    { name: "ECCV", color: "#c05299" },
    { name: "ICCV", color: "#f4845f" },
    { name: "AAAI", color: "#ce4257" },
    { name: "IJCAI", color: "#48cae4" },
    { name: "KDD", color: "#6ca49e" },
    { name: "SIGIR", color: "#edb83f" },
    { name: "SIGGRAPH", color: "#07beb8" },
    { name: "SIGGRAPH Asia", color: "#00a896" },
    { name: "WWW", color: "#a0802e" },
    { name: "ACL", color: "#ff5a5f" },
    { name: "EMNLP", color: "#da5552" },
    { name: "arXiv", color: "#972c32" },
    { name: "TPAMI", color: "#fdc921" },
    { name: "WACV", color: "#2a596d" },
    { name: "JAG", color: "#a3b18a" },
    { name: "RSE", color: "#588157" },
    { name: "TGRS", color: "#d0b17a" },
    { name: "IJCV", color: "#173d5d" },
    { name: "Nature", color: "#31493c" },
    { name: "HRI", color: "#d6b876" },
    { name: "ICDE", color: "#479c3e" },
    { name: "JEM", color: "#a2d2ff" },
    { name: "JSTAR", color: "#ecbf45" },
    { name: "ICRA", color: "#c77dff" },
    { name: "JCLP", color: "#438eac" },
    { name: "IROS", color: "#468faf" },
    { name: "MM", color: "#2a5432" },
    { name: "RSS", color: "#cba637" },
];